-- MySQL Script generated by MySQL Workbench
-- Mon Jun  3 20:09:44 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sistemas_tarefa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistemas_tarefa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistemas_tarefa` DEFAULT CHARACTER SET utf8 ;
USE `sistemas_tarefa` ;

-- -----------------------------------------------------
-- Table `sistemas_tarefa`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistemas_tarefa`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `sistemas_tarefa`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsuario`)
)
ENGINE = InnoDB;

INSERT INTO `sistemas_tarefa`.`Usuario` (`idUsuario`, `nome`, `senha`, `email`) VALUES
(1, 'João', 'senha123', 'joao@example.com'),
(2, 'Maria', 'senha456', 'maria@example.com');

-- -----------------------------------------------------
-- Table `sistemas_tarefa`.`Tarefa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistemas_tarefa`.`Tarefa` ;

CREATE TABLE IF NOT EXISTS `sistemas_tarefa`.`Tarefa` (
  `idTarefa` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NULL,
  `data_tarefa` VARCHAR(45) NULL,
  `data_horaTarefa` VARCHAR(45) NULL,
  `lembrete` VARCHAR(45) NULL,
  `tempoLembrete` VARCHAR(45) NULL,
  `prioridade` VARCHAR(45) NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idTarefa`),
  INDEX `fk_Tarefa_Usuario_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Tarefa_Usuario`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `sistemas_tarefa`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
